spring:
  application:
    name: PocketOfficePool
  datasource:
      url: jdbc:h2:mem:pocket-office-pool
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
      properties:
          hibernate:
              jdbc:
                 time_zone: UTC

api:
  endpoint:
      base-url: /api/v1

server:
    port: 8080